version: "3"

services:
  phoenix:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
